-- DateJared seed data. All normal-user-visible display names remain "Jared".
-- Internal labels are for Jared-only CMS/admin context and should not be rendered
-- in the public swipe deck.

insert into public.jared_profiles (
  slug,
  internal_label,
  display_name,
  age_label,
  location,
  bio,
  prompts,
  tags,
  image_urls,
  sort_order,
  demo,
  active,
  archived_at
) values
(
  'jared-calendar-synced',
  'Calendar-synced Jared',
  'Jared',
  'Early 30s',
  'Two blocks from a reliable grocery store',
  'Keeps plans, reads the confirmation email, and arrives with a backup reservation already saved.',
  '[{"prompt":"A green flag I bring","answer":"I know the difference between flexible and vague."},{"prompt":"Ideal first date","answer":"One drink, one clearly stated end time, and a walk if the weather has earned it."}]'::jsonb,
  array['punctual','dry humor','plans ahead'],
  array['/jared-profile-photos/calendar-synced-1.jpg'],
  10,
  false,
  true,
  null
),
(
  'jared-reads-the-menu',
  'Reads-the-menu Jared',
  'Jared',
  'Mid 30s',
  'Near the place with parking',
  'Has already read the menu, identified two acceptable appetizers, and will not call the server boss.',
  '[{"prompt":"Together we could","answer":"Order efficiently and still leave room for a second location."},{"prompt":"I am unusually good at","answer":"Choosing the table that is neither drafty nor in the server path."}]'::jsonb,
  array['restaurant literate','considerate','quietly decisive'],
  array['/jared-profile-photos/reads-menu-1.jpg'],
  20,
  false,
  true,
  null
),
(
  'jared-emergency-umbrella',
  'Emergency-umbrella Jared',
  'Jared',
  'Early 30s',
  'Somewhere with weather alerts on',
  'Owns a compact umbrella and deploys it without making the moment about preparedness.',
  '[{"prompt":"My most practical trait","answer":"I check the forecast and then remain normal about it."},{"prompt":"Dating me is like","answer":"Finding out the spare phone charger is already in the bag."}]'::jsonb,
  array['prepared','low drama','weather aware'],
  array['/jared-profile-photos/emergency-umbrella-1.jpg'],
  30,
  false,
  true,
  null
),
(
  'jared-neighborhood-regular',
  'Neighborhood-regular Jared',
  'Jared',
  'Mid 30s',
  'A coffee shop that knows the order',
  'Has a regular place but not a regular speech about it. Tips well. Leaves when the chairs go up.',
  '[{"prompt":"The way to my heart","answer":"Remembering that a good booth is a shared resource."},{"prompt":"Best Sunday","answer":"Coffee, errands, and no performative spontaneity."}]'::jsonb,
  array['local','steady','good manners'],
  array['/jared-profile-photos/neighborhood-regular-1.jpg'],
  40,
  false,
  true,
  null
),
(
  'jared-charges-phone',
  'Charges-phone Jared',
  'Jared',
  'Early 30s',
  'Within 15 percent battery confidence',
  'Keeps his phone charged, his read receipts intentional, and his weekend expectations written in complete sentences.',
  '[{"prompt":"I value","answer":"Clear logistics and batteries above 40%."},{"prompt":"A small promise","answer":"If I say I am on my way, I have left the building."}]'::jsonb,
  array['communicative','logistics','reliable'],
  array['/jared-profile-photos/charges-phone-1.jpg'],
  50,
  false,
  true,
  null
),
(
  'jared-brings-a-layer',
  'Brings-a-layer Jared',
  'Jared',
  'Late 30s',
  'The patio, conditionally',
  'Will suggest the patio, bring a layer, and never imply that being cold is a personality test.',
  '[{"prompt":"Simple pleasures","answer":"A patio heater that works and a conversation that does not require shouting."},{"prompt":"I am looking for","answer":"Someone who understands that comfort is not defeat."}]'::jsonb,
  array['patio qualified','practical','warm enough'],
  array['/jared-profile-photos/brings-layer-1.jpg'],
  60,
  false,
  true,
  null
),
(
  'jared-splits-the-check',
  'Splits-the-check Jared',
  'Jared',
  'Mid 30s',
  'A neighborhood with tap-to-pay',
  'Can pay, split, alternate, or discuss it like an adult without turning dinner into a panel.',
  '[{"prompt":"A belief I hold","answer":"Money conversations are easier before the card hits the tray."},{"prompt":"First date energy","answer":"Generous, direct, and not auditioning for a finance podcast."}]'::jsonb,
  array['direct','generous','financially normal'],
  array['/jared-profile-photos/splits-check-1.jpg'],
  70,
  false,
  true,
  null
),
(
  'jared-books-the-thing',
  'Books-the-thing Jared',
  'Jared',
  'Late 30s',
  'Near public transit and one decent bakery',
  'Turns "we should" into a calendar invite, then leaves enough blank space for the day to breathe.',
  '[{"prompt":"My toxic trait","answer":"I think reservations are romantic because they prove intent."},{"prompt":"You should not go out with me if","answer":"You need every plan to become a story."}]'::jsonb,
  array['intentional','calendar invite','low spectacle'],
  array['/jared-profile-photos/books-thing-1.jpg'],
  80,
  false,
  true,
  null
),
(
  'jared-knows-when-to-leave',
  'Knows-when-to-leave Jared',
  'Jared',
  'Early 40s',
  'Close enough to call it a short ride',
  'Understands that a good night can end before everyone starts negotiating one more place.',
  '[{"prompt":"Underrated skill","answer":"Leaving on a high note."},{"prompt":"A date I would repeat","answer":"Good conversation, reasonable lighting, home by mutual agreement."}]'::jsonb,
  array['self-aware','boundaries','good exits'],
  array['/jared-profile-photos/knows-when-to-leave-1.jpg'],
  90,
  false,
  true,
  null
),
(
  'jared-replies-after-work',
  'Replies-after-work Jared',
  'Jared',
  'Mid 30s',
  'Usually in a quiet corner',
  'Replies after work because work was happening. Does not confuse silence with strategy.',
  '[{"prompt":"Texting style","answer":"Responsive, not ambient."},{"prompt":"What I appreciate","answer":"People who can be unavailable without becoming mysterious."}]'::jsonb,
  array['responsive','adult schedule','not mysterious'],
  array['/jared-profile-photos/replies-after-work-1.jpg'],
  100,
  false,
  true,
  null
),
(
  'jared-owns-a-real-coat',
  'Owns-a-real-coat Jared',
  'Jared',
  'Late 30s',
  'Where winter is not theoretical',
  'Owns a real coat and treats seasonal reality as information, not a challenge.',
  '[{"prompt":"A practical flex","answer":"I dress for the actual temperature."},{"prompt":"Compatibility test","answer":"Can we be warm and still interesting?"}]'::jsonb,
  array['seasonally aware','grounded','warm'],
  array['/jared-profile-photos/real-coat-1.jpg'],
  110,
  false,
  true,
  null
),
(
  'jared-saves-the-receipt',
  'Saves-the-receipt Jared',
  'Jared',
  'Early 40s',
  'A short walk from the useful entrance',
  'Saves receipts, remembers preferences, and considers "I took care of it" a complete sentence.',
  '[{"prompt":"My love language","answer":"Quiet follow-through."},{"prompt":"Best case scenario","answer":"We both feel considered and nobody has to make a speech about it."}]'::jsonb,
  array['follow-through','observant','useful'],
  array['/jared-profile-photos/saves-receipt-1.jpg'],
  120,
  false,
  true,
  null
)
on conflict (slug) do update set
  internal_label = excluded.internal_label,
  display_name = excluded.display_name,
  age_label = excluded.age_label,
  location = excluded.location,
  bio = excluded.bio,
  prompts = excluded.prompts,
  tags = excluded.tags,
  image_urls = excluded.image_urls,
  sort_order = excluded.sort_order,
  demo = excluded.demo,
  active = excluded.active,
  archived_at = excluded.archived_at,
  updated_at = now();
