-- DateJared seed data. All normal-user-visible display names remain "Jared".
-- Internal labels are for Jared-only CMS/admin context and should not be rendered
-- in the public swipe deck.

insert into public.jared_profiles (
  slug,
  internal_label,
  display_name,
  age_label,
  location,
  bio,
  prompts,
  tags,
  image_urls,
  sort_order,
  demo_eligible,
  active,
  archived
) values
(
  'jared-dinner-conversation',
  'Dinner / conversation Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'I like good conversation, warm lighting, and the part of dinner where everyone stops pretending they are not going to order fries.',
  '[{"prompt":"Ideal first date","answer":"Dinner somewhere with warm lighting, then a walk if neither of us has started checking the time."},{"prompt":"A green flag I bring","answer":"I can hold a conversation without turning it into a podcast audition."}]'::jsonb,
  array['Dinner','conversation','Oakland','movies'],
  array['/jared-profile-photos/dinner-conversation-1.jpg'],
  10,
  true,
  true,
  false
),
(
  'jared-systems-software',
  'Systems / software Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Software engineer. Good at systems. Still refining a few human-facing interfaces.',
  '[{"prompt":"I am unusually good at","answer":"Finding the edge case and then, eventually, making eye contact."},{"prompt":"Together we could","answer":"Debug a plan until it becomes a date."}]'::jsonb,
  array['software','systems','dry humor','Oakland'],
  array['/jared-profile-photos/systems-software-1.jpg'],
  20,
  true,
  true,
  false
),
(
  'jared-cooking-home',
  'Cooking / home Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Can cook one impressive thing and several adequate things. Knows which is which.',
  '[{"prompt":"My most practical trait","answer":"I clean while cooking, not as a moral performance but because counters are finite."},{"prompt":"A small promise","answer":"If I say dinner is almost ready, it is within a defensible range of almost."}]'::jsonb,
  array['cooking','home','dinner','honest'],
  array['/jared-profile-photos/cooking-home-1.jpg'],
  30,
  true,
  true,
  false
),
(
  'jared-fitness-routine',
  'Fitness / routine Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Trying to be more consistent about the gym. Currently in a promising but legally non-binding phase.',
  '[{"prompt":"Simple pleasures","answer":"A routine that survives one mildly inconvenient week."},{"prompt":"You should not go out with me if","answer":"You need fitness updates delivered with influencer lighting."}]'::jsonb,
  array['fitness','routine','gym','self-aware'],
  array['/jared-profile-photos/fitness-routine-1.jpg'],
  40,
  true,
  true,
  false
),
(
  'jared-coffee-planning',
  'Coffee / planning Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Overthinks the coffee shop, then somehow picks the obvious one.',
  '[{"prompt":"Texting style","answer":"Clear enough to make the plan, restrained enough not to become a meeting agenda."},{"prompt":"Ideal first date","answer":"Coffee that can become a walk but is not legally required to."}]'::jsonb,
  array['coffee','planning','Oakland','walks'],
  array['/jared-profile-photos/coffee-planning-1.jpg'],
  50,
  true,
  true,
  false
),
(
  'jared-parks-outdoors-ish',
  'Parks / outdoors-ish Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Open to nature, especially when nature has parking and a clear plan for snacks.',
  '[{"prompt":"Best Sunday","answer":"A park, a coffee, and a route that does not become a survival narrative."},{"prompt":"Compatibility test","answer":"Can we enjoy a view without pretending we discovered outside?"}]'::jsonb,
  array['parks','outdoors-ish','snacks','Oakland'],
  array['/jared-profile-photos/parks-outdoors-ish-1.jpg'],
  60,
  true,
  true,
  false
),
(
  'jared-sincere-romantic',
  'Sincere / romantic Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Sincere underneath several layers of dry delivery.',
  '[{"prompt":"The way to my heart","answer":"Notice the effort, then meet me where sincerity is quiet and clear."},{"prompt":"I value","answer":"Kindness with a working sense of timing."}]'::jsonb,
  array['sincere','romantic','dry delivery','kind'],
  array['/jared-profile-photos/sincere-romantic-1.jpg'],
  70,
  true,
  true,
  false
),
(
  'jared-product-constrained-market',
  'Product / constrained market Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'I keep things clear, show up on time, and stay curious about what makes connection feel real.',
  '[{"prompt":"My toxic trait","answer":"I over-explain small choices and then need to remember what matters in the moment."},{"prompt":"Together we could","answer":"Build a date around honesty, good conversation, and a plan that fits both of our lives."}]'::jsonb,
  array['steady','honest','thoughtful','Oakland'],
  array['/jared-profile-photos/product-constrained-market-1.jpg'],
  80,
  true,
  true,
  false
),
(
  'jared-calendar-synced',
  'Calendar-synced Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Keeps plans, reads the confirmation email, and arrives with a backup reservation already saved.',
  '[{"prompt":"A green flag I bring","answer":"I know the difference between flexible and vague."},{"prompt":"Ideal first date","answer":"One drink, one clearly stated end time, and a walk if the weather has earned it."}]'::jsonb,
  array['punctual','dry humor','plans ahead','Oakland'],
  array['/jared-profile-photos/calendar-synced-1.jpg'],
  90,
  true,
  true,
  false
),
(
  'jared-brings-a-layer',
  'Brings-a-layer Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Will suggest the patio, bring a layer, and never imply that being cold is a personality test.',
  '[{"prompt":"Simple pleasures","answer":"A patio heater that works and a conversation that does not require shouting."},{"prompt":"I am looking for","answer":"Someone who understands that comfort is not defeat."}]'::jsonb,
  array['patio','practical','warm enough','conversation'],
  array['/jared-profile-photos/brings-layer-1.jpg'],
  100,
  true,
  true,
  false
),
(
  'jared-replies-after-work',
  'Replies-after-work Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Replies after work because work was happening. Does not confuse silence with strategy.',
  '[{"prompt":"Texting style","answer":"Responsive, not ambient."},{"prompt":"What I appreciate","answer":"People who can be unavailable without becoming mysterious."}]'::jsonb,
  array['responsive','adult schedule','not mysterious','Oakland'],
  array['/jared-profile-photos/replies-after-work-1.jpg'],
  110,
  true,
  true,
  false
),
(
  'jared-saves-the-receipt',
  'Saves-the-receipt Jared',
  'Jared',
  '30-ish',
  'Oakland',
  'Saves receipts, remembers preferences, and considers "I took care of it" a complete sentence.',
  '[{"prompt":"My love language","answer":"Quiet follow-through."},{"prompt":"Best case scenario","answer":"We both feel considered and nobody has to make a speech about it."}]'::jsonb,
  array['follow-through','observant','useful','quiet'],
  array['/jared-profile-photos/saves-receipt-1.jpg'],
  120,
  true,
  true,
  false
)
on conflict (slug) do update set
  internal_label = excluded.internal_label,
  display_name = excluded.display_name,
  age_label = excluded.age_label,
  location = excluded.location,
  bio = excluded.bio,
  prompts = excluded.prompts,
  tags = excluded.tags,
  image_urls = excluded.image_urls,
  sort_order = excluded.sort_order,
  demo_eligible = excluded.demo_eligible,
  active = excluded.active,
  archived = excluded.archived,
  updated_at = now();
